name: Build Release

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tag
        run: |
          major=$(jq -r '.version.major' app_version.json)
          minor=$(jq -r '.version.minor' app_version.json)
          patch=$(jq -r '.version.patch' app_version.json)
          version_name=v$major.$minor.$patch
          git tag -a "$version_name" -m "Release $version_name"
          git push origin tag "$version_name"

#  build:
#    name: Generate Release App
#    runs-on: ubuntu-latest
#    timeout-minutes: 90
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Validate Gradle Wrapper
#        uses: gradle/wrapper-validation-action@v1
#
#      - name: Copy CI Gradle Properties
#        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
#
#      - name: Setup JDK 11
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: '11'
#
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#
#      - name: Build App
#        run: ./gradlew bundleRelease
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: aab
#          path: app/build/outputs/bundle/release/app-release.aab
#
#  release:
#    needs: build
#    name: Create Release
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download Artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: aab
#
#      - name: Create Release Draft
#        uses: softprops/action-gh-release@v1
#        with:
#          draft: true
#          prerelease: false
#          fail_on_unmatched_files: true
#          files: app-release.aab