name: Build Debug

on:
  pull_request:
    types: [ closed ]
    branches: [ development ]

concurrency:
  group: build_debug_${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Generate Debug App
    if: ${{ startsWith(github.head_ref, 'feature/') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI Gradle Properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build App
        run: ./gradlew assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Print Disk Space Usage
        if: failure()
        run: df -h

  upload:
    needs: build
    runs-on: ubuntu-latest
    name: Upload to Firebase
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: apk

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Setup Firebase CLI
        run: |
          npm install -g firebase-tools
          echo "${{ secrets.CREDENTIAL_FILE_CONTENT }}" > firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account.json

      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute $FILE --app $APP_ID --groups $GROUP --release-name "$RELEASE_NAME"
        env:
          FILE: app-debug.apk
          APP_ID: ${{ secrets.FIREBASE_APP_ID_DEV }}
          GROUP: testers
          RELEASE_NAME: ${{ github.head_ref }}