name: Build Debug

on: workflow_dispatch

jobs:
  assemble_job:
    needs: [ lint_check_job ]
    name: Generate Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Get current date
        id: date
        run: |
          echo "current=$(date +'%Y.%m.%d.%H.%M')" >> "$GITHUB_OUTPUT"

      - name: Get version name
        id: version
        run: |
          echo "name=$(${{github.workspace}}/gradlew -q getVersionName)" >> "$GITHUB_OUTPUT"

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: "com.syalim.edufundtest.debug-v${{ steps.version.outputs.name }}-${{ steps.date.outputs.current }}.apk"
          path: app/build/outputs/apk/debug/**.apk
