name: Build

on:
  workflow_run:
    workflows: [ Lint Check ]
    types: [ completed ]
    branches:
      - master
      - development
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build Apps
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.head_commit.message, '[build]')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI Gradle Properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build App
        run: ./gradlew assemble

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: APKs
          path: app/build/outputs/apk/**/**.apk