name: Build Debug

on:
  pull_request:
    types: [ closed ]
    branches: [ development ]

concurrency:
  group: build_debug_${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Generate Debug App
    if: ${{ startsWith(github.head_ref, 'feature/') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI Gradle Properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build App
        run: ./gradlew assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Print Disk Space Usage
        if: failure()
        run: df -h

  upload:
    needs: build
    name: Upload to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: apk

      - name: Upload
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_DEV }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app-debug.apk
          releaseNotes: ${{ github.head_ref }}