name: Build

on:
  push:
    branches:
      - master
      - development
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  lint_check:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy ci-gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: lint-report.html
          path: app/build/reports/lint-results-debug.html

  build:
    needs: [ lint_check]
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: contains(github.event.head_commit.message, '[build]')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI Gradle Properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build App
        run: ./gradlew assemble

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: APKs
          path: app/build/outputs/apk/**/**.apk