name:

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  lint_check_job:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Lint Check
        run: ./gradlew lintDebug

      - name: Upload Lint Report
        uses: actions/upload-artifact@v2
        with:
          name: lint-report.html
          path: app/build/reports/lint-results-debug.html

  dependency_check_job:
    needs: [ lint_check_job ]
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Dependency Check
        run: ./gradlew dependencyUpdates

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report.txt
          path: build/dependencyUpdates/report.text
