name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Generate Release App
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI Gradle Properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build App
        run: ./gradlew bundleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: aab
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Print Disk Space Usage
        if: failure()
        run: df -h

  release:
    needs: build
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: aab

      - name: Create Release Draft
      - uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref }}
          tag: ${{ github.ref }}
          draft: true
          artifacts: app-release.aab
          artifactContentType: application/zip
          allowUpdates: true

#      - name: Create Release Draft
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: ${{ github.ref }}
#          draft: true
#          prerelease: false
#
#      - name: Upload Asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: app-release.aab
#          asset_name: app-release.aab
#          asset_content_type: application/zip