name: Create Version Branch

on:
  workflow_dispatch:
    inputs:
      bump_version:
        description: Bump Version
        required: true
        default: Patch
        type: choice
        options:
          - Major
          - Minor
          - Patch

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Head
        uses: actions/checkout@v4

      - name: Generate New Version
        id: new_version
        run: |
          bump_version="${{ inputs.bump_version }}"
          major=$(jq -r '.version.major' app_version.json)
          minor=$(jq -r '.version.minor' app_version.json)
          patch=$(jq -r '.version.patch' app_version.json)
          if [ "$bump_version" = "Major" ]; then
            major=$((major + 1))
          elif [ "$bump_version" = "Minor" ]; then
            minor=$((minor + 1))
          elif [ "$bump_version" = "Patch" ]; then
            patch=$((patch + 1))
          fi
          echo "major=$major" >> "$GITHUB_OUTPUT"
          echo "minor=$minor" >> "$GITHUB_OUTPUT"
          echo "patch=$patch" >> "$GITHUB_OUTPUT"
          echo "name=v$major.$minor.$patch" >> "$GITHUB_OUTPUT"

      - name: Create Branch
        run: |
          branch_name="${{ steps.new_version.outputs.name }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b "$branch_name"
          git push origin "$branch_name"

      - name: Update app_version.json
        run: |
          jq '(.version.major = ${{ steps.new_version.outputs.major }}) | (.version.minor = ${{ steps.new_version.outputs.minor }}) | (.version.patch = ${{ steps.new_version.outputs.patch }})' app_version.json > app_version.json.tmp && mv app_version.json.tmp app_version.json
          git add .
          git commit -m "Bumped version to ${{ steps.new_version.outputs.name }}"
          git push origin "${{ steps.new_version.outputs.name }}"