name: Build Debug

on: workflow_dispatch

concurrency:
  group: build_debug_${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Generate debug APK
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy ci-gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set APK name params
        id: params
        run: |
          echo "current_date=$(date +'%Y.%m.%d.%H.%M')" >> "$GITHUB_OUTPUT"
          echo "version_name=$(${{github.workspace}}/gradlew -q getVersionName)" >> "$GITHUB_OUTPUT"

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: "com.syalim.edufundtest.debug-v${{ steps.params.outputs.version_name }}-${{ steps.params.outputs.current_date }}.apk"
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Print disk space usage
        if: failure()
        run: df -h
