name: Lint Check

on:
  pull_request:
    types:
      - closed
    branches: [ master, development ]
  workflow_dispatch:

jobs:
  lint_check_job:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Get current date
        id: params
        run: |
          echo "current_date=$(date +'%Y.%m.%d.%H.%M')" >> "$GITHUB_OUTPUT"
          echo "version_name=$(${{github.workspace}}/gradlew -q getVersionName)" >> "$GITHUB_OUTPUT"

      - name: Upload lint report
        uses: actions/upload-artifact@v3
        with:
          name: "lint-report-v${{ steps.params.outputs.version_name }}-${{ steps.params.outputs.current_date }}.html"
          path: app/build/reports/lint-results-debug.html

