name: Lint Check

on:
  pull_request:
    types:
      - closed
    branches: [ master, development ]

jobs:
  lint_check_job:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Get current date
        id: date
        run: |
          echo "current=$(date +'%Y.%m.%d.%H.%M')" >> "$GITHUB_OUTPUT"

      - name: Upload lint report
        uses: actions/upload-artifact@v3
        with:
          name: "lint-report-${{ steps.date.outputs.current }}.html"
          path: app/build/reports/lint-results-debug.html

