name: Release

on:
  workflow_dispatch:
    inputs:
      priority:
        description: Release Priority
        required: true
        default: 0
        type: choice
        options:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5

jobs:
  build-app:
    runs-on: ubuntu-latest
    name: Generate Release App
    if: github.ref == 'refs/heads/master'
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy CI Gradle Properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build App
        run: ./gradlew bundleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: aab
          path: app/build/outputs/bundle/release/app-release.aab

  create-tag:
    needs: [ build-app ]
    name: Create Version Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Tag Version
        run: |
          props=$(cat app-version.properties)
          version_major=$(echo "$props" | grep -E "version_major=" | cut -d'=' -f2)
          version_minor=$(echo "$props" | grep -E "version_minor=" | cut -d'=' -f2)
          version_patch=$(echo "$props" | grep -E "version_patch=" | cut -d'=' -f2)
          echo "TAG_VERSION=v$version_major.$version_minor.$version_patch" >> "$GITHUB_ENV"

      - name: Push Tag
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git tag -a $TAG_VERSION
          git push origin tag $TAG_VERSION

  create-release:
    needs: [ create-tag ]
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: aab

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          fail_on_unmatched_files: true
          files: app-release.aab
          generate_release_notes: true