name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Generate release bundle
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy ci-gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set bundle name params
        id: params
        run: |
          echo "version_name=$(${{github.workspace}}/gradlew -q getVersionName)" >> "$GITHUB_OUTPUT"

      - name: Build bundle
        run: ./gradlew bundleRelease

      - name: Upload Bundle
        uses: actions/upload-artifact@v3
        with:
          name: "com.syalim.edufundtest-v${{ steps.params.outputs.version_name }}.aab"
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Print disk space usage
        if: failure()
        run: df -h
